### ISSUE TITLE
Shelter does not detect enabled work profile on Samsung S9, crashes

### ISSUE THREAD

**Issue by Wyrrrd** [PeterCxy/Shelter#56] opened 2019-03-01 08:05 UTC
I was recently updating to Shelter v1.4 from 1.3 on my Samsung S9. The unfreeze shortcuts suddenly stopped working. When I tried to access the App, it closed immediately and greeted me with a toast message saying:

![screenshot_20190301-083500_samsung experience home](https://user-images.githubusercontent.com/11527443/53623978-f59dc400-3bfe-11e9-9376-86fd43a0c657.jpg)

The work profile is still active. I disabled and reenabled it, tried again, reinstalled Shelter, tried again... always getting the message above.

**Model:** SM-G960F
**Software:** Stock Firmware (Android 9 "Pie")
**Security Patches:** 01. February 2019

Thanks in advance. If you need further info, just ask :)

**Comment by PeterCxy** [comment] 2019-03-06 04:52
Could be a regression introduced by 05492af180180c985590e467b7f7e97ae2909b86. But I'm not sure why it's all fine on my devices.

**Comment by PeterCxy** [comment] 2019-03-06 04:58
Since I can't reproduce this bug, all I can do now is guessing. I can try to revert that suspicious change and upload an apk here for you guys who encountered this problem to test, but I am too busy recently so it might be a few days or even weeks before I can get into this again.

**Comment by Wyrrrd** [comment] 2019-03-07 16:47
I just dropped Shelter and the sheltered apps on the affected phone (no problem since it is not my primary phone), so no hurry on my end. I will still be available for testing though.

**Comment by brianbienvenu** [comment] 2019-03-08 08:39
I'm seeing the same error as Wyrrrd on my Note 9 with latest stock ROM. Happens across reboots, after deleting the Work Profile and reinstalling Shelter. I'm a new user to Shelter, setting it up for the first time. 

Model: SM-N960F
Software: Stock Firmware (Android 9 "Pie")
Security Patches: 01. February 2019

Happy to run test builds if you have anything to try out, I'd love to get this working.

FWIW, after Sheler failed, I tried out Island. It also fails with some error, stating that I already had another Work Profile that I needed to delete, even when I didn't).

**Comment by PeterCxy** [comment] 2019-03-10 11:44
[app-release.zip](https://github.com/PeterCxy/Shelter/files/2949400/app-release.zip)

Could you please try this apk with the suspicious commit reverted to see if it works again? If so, I might have some idea on how to fix it. If not, then I really have no idea..

**Comment by brianbienvenu** [comment] 2019-03-10 12:12
Works perfectly!

What was that commit trying to fix?

**Comment by PeterCxy** [comment] 2019-03-10 12:29
That commit added authentication to cross-profile Intent contents that Shelter uses. Apparently the sorting of content items broke on some devices, but not on the others, causing the Intent content to be non-reproducible.

Well, I might just revert it for now.

**Comment by PeterCxy** [comment] 2019-03-10 12:41
I have uploaded Shelter 1.4.1 as a fix for the problem. Sorry for you guys that experienced this, it was really unexpected. I'm closing this since it has been resolved.

**Closed by PeterCxy** 2019-03-10 12:41 UTC

**Comment by Wyrrrd** [comment] 2019-03-14 12:12
ersion 1.4.1 works like a charm, thank you.

**Comment by joergister** [comment] 2020-03-23 11:10
I can confirm Version 1.4.1 does work but the latest version on the play store (1.5) does have the issue described here on a OnePlus 3 running latest official LinageOS 16.0 (android 9). Had to downgrade to shelter Version 1.4.1.
